version: '3.4'

services:
  catalogdb:
    image: mongo
    volumes:
      - catalogdb:/data/db 

  basketdb:
    image: redis:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes:
  catalogdb:
